name: Build and Push to DockerHub

env:
    CONTEXT_DIR: './'
    IMAGE_NAME: ${{ github.repository }}

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
                  echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
                  echo "FULL_IMAGE_NAME=$IMAGE_NAME:$(date +%s)" >> $GITHUB_ENV
            - name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and Push Release to DockerHub
              shell: bash
              run: scripts/build.sh
